name: Run Rubocop and RSpec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rubocop:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run Rubocop
        run: bundle exec rake rubocop

  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']
        mysql-version: ['5.7', '8.0']

    steps:
      - uses: actions/checkout@v2
      - uses: ankane/setup-mysql@v1
        with:
          mysql-version: ${{ matrix.mysql-version }}
      - name: Create the test database
        run: mysqladmin create rails_cursor_pagination_testing
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run tests
        run: bundle exec rake spec
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
